%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/savnik/Documents/BSc/mobotware-3.598/rhd/trunk/pingTest.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/01/12 19:00:55

%% Initialize variables.
clear all;
close all;

filename = 'pingTest.txt';
delimiter = {',',' ','='};
startRow = 2;
n = 100; % Sample number
endRow = n+startRow;

% Format string for each line of text:
%   column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%*s%*s%*s%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'ReturnOnError', false);

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

% Allocate imported array to column variable names
VarName10 = dataArray{:, 1};

% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;
M = (VarName10(:)');
ms_mean = mean(M,1);

hold on;
plot(VarName10);
xlabel('Ping sample n');
ylabel('Response time [ms]');
title('Response time between GCS and FCS');
xlim([0 n]);
hold off;