#!/bin/bash
#
# Setup Beaglebone Black to Ground Station, RHD part
# 
# Author: Peter Savnik
# 2015

echo "	* Setting up Phidget Library"
echo "	* Unpack"
tar -xzf libphidget_2.1.8.20140319.tar.gz
rm libphidget_2.1.8.20140319.tar.gz
cd libphidget-2.1.8.20140319
echo "	* Configre"
./configure --disable-jni
echo "	* Make"
make
echo "	* make install"
make install
echo "	* Copy rules"
cd ../
cp 99-phidgets.rules /etc/udev/rules.d/

echo "	*** Done! ***"