#!/bin/bash
#
# Setup Beaglebone Black to Ground Station, RHD part
# 
# Author: Peter Savnik
# 2015

echo ""
echo "*** Setting up IO ***"
echo ""
# Create links $SLOTS and $PINS
export SLOTS=/sys/devices/bone_capemgr.9/slots
export PINS=/sys/kernel/debug/pinctrl/44e10800.pinmux/pins

echo "Setup Device Tree"
# Create device tree
cd plugins/tcuav/overlay
./build
cd ../../../
# Copy device tree to firmware

cp plugins/tcuav/overlay/DM-GPIO-Test-00A0.dtbo /lib/firmware/

echo "Enable am33xx_pwm"
echo am33xx_pwm > $SLOTS
echo "Enable DM-GPIO-Test"
echo DM-GPIO-Test > $SLOTS
echo "Enable bone_pwm_P9_14"
echo bone_pwm_P9_14 > $SLOTS

cat $SLOTS

echo ""
echo "*** rhd link ***"
echo ""
export PATH="$PATH:/home/debian/rhd/trunk/build/bin"

echo ""
echo "**** Done! ****"